### ISSUE TITLE
More than 1 Airco

### ISSUE THREAD

**Issue by alexander250100** [MiguelAngelLV/esphaier#23]
I am a noob, I managed to get one Haier to work on this great piece of software.  I do not understand how to get another to work.
When flashing again on another ESp, it is a clone and it sees two ESP's as the same. I tried to rename the files but no luck. Only one airco will work when two are connected with HA.

Anyone can help, thanks!

**Comment by miguelangellv** [comment]
You need change "name" fields in the file too before of flash

Line 2:
https://github.com/MiguelAngelLV/esphaier/blob/master/esphaier.yaml#L2


And line 35
https://github.com/MiguelAngelLV/esphaier/blob/master/esphaier.yaml#L38

**Comment by alexander250100** [comment]
Thank you sir, the linenumbers are different with me, I will change the text. Only this two because line 36 in your note says return "Haier".?

**Comment by miguelangellv** [comment]
You need change
**name: Haier** for **name: Haier Bedroom** for example.

Haier is the name for device, not for "model".

**Comment by alexander250100** [comment]
thanks for your help and patience, also need to change H file?

**Comment by miguelangellv** [comment]
No, you only need change the .yaml

**Comment by alexander250100** [comment]
Last question, got error:  was not declared in this scope when changing name from haier to haierdaan. Sorry for bothering you again.

**Comment by miguelangellv** [comment]
Please, copy all your yaml (no passwords)

**Comment by alexander250100** [comment]
```yaml

esphome:
  name: haierdaan
  platform: ESP8266
  board: esp01_1m
  includes:
    - Haier.h
globals:
  - id: control_command 
    type: byte[64]
    restore_value: no
    initial_value: '{HEADER,HEADER,20,64,0,0,0,0,0,1,SEND_COMMAND}' #this is the header, the rest of the message is the status/control
    
logger:
  level: DEBUG
  baud_rate: 0 #Important. You can't use serial port
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.1.10
    
api:
# Enable Home Assistant API
ota:

web_server:

switch:
  - platform: template
    name: "Screen"
    id: display_status
    icon: mdi:monitor-eye
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA1_OFFSET], DISPLAY_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA1_OFFSET], DISPLAY_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA1_OFFSET], DISPLAY_BIT);
          sendData(id(control_command));
  - platform: template
    name: "Use Fahrenheit"
    id: units_status
    icon: mdi:temperature-fahrenheit
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA1_OFFSET], F_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA1_OFFSET], F_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA1_OFFSET], F_BIT);
          sendData(id(control_command));
  - platform: template
    name: "Health Mode"
    id: purify_status
    icon: mdi:shimmer
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA2_OFFSET], HEALTH_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA2_OFFSET], HEALTH_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA2_OFFSET], HEALTH_BIT);
          sendData(id(control_command));
  - platform: template
    name: "Self Clean"
    id: self_clean_status
    icon: mdi:liquid-spot
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA3_OFFSET], SELF_CLEAN_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA3_OFFSET], SELF_CLEAN_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA3_OFFSET], SELF_CLEAN_BIT);
          sendData(id(control_command));
  - platform: template
    name: "Steri Clean 56C"
    id: steri_clean_status
    icon: mdi:liquid-spot
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA1_OFFSET], SELF_CLEAN56_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA1_OFFSET], SELF_CLEAN56_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA1_OFFSET], SELF_CLEAN56_BIT);
          sendData(id(control_command));
  - platform: template
    name: "Controls Lock"
    id: lock_status
    icon: mdi:remote-off
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA2_OFFSET], LOCK_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA2_OFFSET], LOCK_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA2_OFFSET], LOCK_BIT);
          sendData(id(control_command));
  - platform: template
    name: "Supplamental Heat"
    id: supp_heat
    icon: mdi:heating-coil
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA2_OFFSET], ELECTRIC_HEAT_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA2_OFFSET], ELECTRIC_HEAT_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA2_OFFSET], ELECTRIC_HEAT_BIT);
          sendData(id(control_command));
  - platform: template
    name: "Beeper"
    id: echo_status
    icon: mdi:volume-high
    restore_state: true
    optimistic: true
  - platform: template
    name: "Fresh Air"
    id: fresh_mode
    icon: mdi:weather-windy
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA3_OFFSET], FRESH_AIR_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA3_OFFSET], FRESH_AIR_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA3_OFFSET], FRESH_AIR_BIT);
          sendData(id(control_command));
  - platform: template
    name: "Light Status"
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA3_OFFSET], LIGHT_STATUS_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA3_OFFSET], LIGHT_STATUS_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA3_OFFSET], LIGHT_STATUS_BIT);
          sendData(id(control_command));
  - platform: template
    name: "Energy Save Status"
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA3_OFFSET], ENERGY_SAVE_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA3_OFFSET], ENERGY_SAVE_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA3_OFFSET], ENERGY_SAVE_BIT);
          sendData(id(control_command));
  - platform: template
    name: "Filter"
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA3_OFFSET], FILTER_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA3_OFFSET], FILTER_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA3_OFFSET], FILTER_BIT);
          sendData(id(control_command));
  - platform: template
    name: "Intelligence"
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA1_OFFSET], INTELLIGENCE_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA1_OFFSET], INTELLIGENCE_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA1_OFFSET], INTELLIGENCE_BIT);
          sendData(id(control_command));
  - platform: template
    name: "Pulse Motor Valve"
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA1_OFFSET], PMV_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA1_OFFSET], PMV_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA1_OFFSET], PMV_BIT);
          sendData(id(control_command));
  - platform: template
    name: "Energy Save"
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA1_OFFSET], ENERGY_SAVE_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA1_OFFSET], ENERGY_SAVE_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA1_OFFSET], ENERGY_SAVE_BIT);
          sendData(id(control_command));
  - platform: template
    name: "Half Degree"
    lambda: |-
        return bitRead(id(control_command)[STATUS_DATA1_OFFSET], HALF_DEGREE_BIT);
    turn_on_action:
      - lambda: |-
          bitSet(id(control_command)[STATUS_DATA1_OFFSET], HALF_DEGREE_BIT);
          sendData(id(control_command));
    turn_off_action:
      - lambda: |-
          bitClear(id(control_command)[STATUS_DATA1_OFFSET], HALF_DEGREE_BIT);
          sendData(id(control_command));

sensor:
  - platform: template
    id: outdoor_temp
    name: "Outdoor Temperature"
    update_interval: 5s
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "measurement"
    lambda: |-
            return ((id(control_command)[OUTDOOR_TEMP])/2.0)-20; //offset of 25

climate:
  - platform: custom
    lambda: |-
      auto haierdaan = new Haierdaan();
      App.register_component(haierdaan);
      return {haierdaan};
    climates:
      - name: "Haier_AC"
```
